<?php /* var $this Pure360_Common_Block_Adminhtml_System_Config_About */ ?>

<div style="background-color: #f4f9f5; border: 1px solid #D6D6D6; margin-bottom: 10px; padding: 10px 5px 15px 30px; color: #000">
	<a href="http://www.pure360.com" target="_blank"><img src="<?php echo $this->getSkinUrl('images/pure360/pure_logo.png'); ?>" alt="Pure360" style="float: left; margin-right: 20px;"/></a>
	<strong>Improving your email marketing &amp; SMS results together</strong><br/>
	Call Pure360 on 08082 562353<br/>
	<a href="http://www.pure360.com">http://www.pure360.com</a><br/>
</div>