<fieldset>
	<div class="col-1">
		<a href="http://www.pure360.com" target="_blank"><img src="<?php echo $this->getSkinUrl('images/pure360/pure_logo.png'); ?>" alt="Pure360" class="logo-pure360"/></a>
		
		<strong>Improving your email marketing &amp; SMS results together</strong><br/>
		Call Pure360 on 0844 273 6401<br/>
		<a href="http://www.pure360.com">http://www.pure360.com</a><br/>
	</div>
</fieldset>