<?php
	$scope = Mage::helper('pure360_common')->getScope();
	$scopeId = Mage::helper('pure360_common')->getScopeId();
?>
<script type="text/javascript">
	//<![CDATA[
    function initPure360Trigger() 
	{
		pure360Trigger = new Pure360Trigger(
			'<?php echo $scope; ?>',
			'<?php echo $scopeId; ?>',
			'<?php echo $this->getUrl('pure360_cart/Ajax/saveTriggers'); ?>',
			'<?php echo $this->getUrl('pure360_cart/Ajax/clearCarts'); ?>');
	}
	//]]>
</script>

