<?php if($this->isEnabled()): ?>

	<script>
		function prepareNewsletterField() {
			Element.show('register-customer-newsletter');

			if (checkout.method == 'register') {
	<?php echo $this->getJsCheckedCode('register'); ?>
			} else if (checkout.method == 'guest') {
	<?php echo $this->getJsCheckedCode('guest'); ?>
			} else {
	<?php echo $this->getJsCheckedCode('customer'); ?>
			}
		}

		function setSubscribedValue(checkbox)
		{
			var checked = checkbox.checked ? 1 : 0;
			var original = $('billing:is_subscribed_original').value;

			if (checked != original) {
				$('billing:is_subscribed').value = checked;
			} else {
				$('billing:is_subscribed').value = original;
			}

			return false;
		}

		Event.observe(window, 'load', function() {
			if ($('onepage-guest-register-button') != null) {
				Event.observe('onepage-guest-register-button', 'click', function() {
					prepareNewsletterField();
				});
			}
			$$('#co-billing-form fieldset')[0].insert('<span id="register-customer-newsletter" style="display:none;"></span>')
			$$('#co-billing-form fieldset #register-customer-newsletter')[0].insert('<style>.col1-layout .billing_is_subscribed_box { margin-left: 240px !important; } .col1-layout #billing_subscribed_label { text-align: left; }</style>');

			$$('#co-billing-form fieldset #register-customer-newsletter')[0].insert(
					'<br />' +
					'<div class="">' +
					'<input id="billing:is_subscribed_original" type="hidden" name="billing[is_subscribed_original]" value="1" />' +
					'<input id="billing:is_subscribed" type="hidden" name="billing[is_subscribed]" value="1" />' +
					'<input id="billing:is_subscribed_box" class="billing_is_subscribed_box" type="checkbox" onchange="setSubscribedValue(this); return false;" checked="checked" title="<?php echo $this->__($this->getCheckboxLabelText()) ?>" style="float:left; width: auto; margin: 2px 8px 0 0;" />' +
					'<strong><span><label id="billing_subscribed_label" for="billing[is_subscribed]"><?php echo $this->__($this->getCheckboxLabelText()) ?></label></span></strong>' +
					'</div>' +
					'');

			prepareNewsletterField();
		});
	</script>

<?php endif ?>