<?php if($this->isEnabled()): ?>

	<script>
		function loadSubscribedField() {
			Element.show('customer-subscribe');

			if (checkout.method == 'register') {
				<?php echo $this->getJsCheckedCode('register'); ?>
			} else if (checkout.method == 'guest') {
				<?php echo $this->getJsCheckedCode('guest'); ?>
			} else {
				<?php echo $this->getJsCheckedCode('customer'); ?>
			}
		}

		function setSubscribedValue(checkbox)
		{
			var checked = checkbox.checked ? 1 : 0;
			var original = $('billing:is_subscribed_original').value;

			if (checked != original) {
				$('billing:is_subscribed').value = checked;
			} else {
				$('billing:is_subscribed').value = original;
			}

			return false;
		}

		Event.observe(window, 'load', function() {
			
			if ($('onepage-guest-register-button') != null) {
				Event.observe('onepage-guest-register-button', 'click', function() {
					loadSubscribedField();
				});
			}
			
			$$('#co-billing-form fieldset ul').first().insert(
				'<li><!-- --></li>' +
				'<li class="control" id="customer-subscribe" style="display:none;">' +
				'<input name="billing[is_subscribed]" id="billing:is_subscribed_box" value="1" checked="checked" title="Ship to this address" onchange="setSubscribedValue(this); return false;" class="checkbox" type="checkbox" />' +
				'<label for="billing:is_subscribed_box"><?php echo $this->__($this->getCheckboxLabelText()) ?></label>' +
				'</li>'
			);
			
			$$('#co-billing-form fieldset')[0].insert(
					'<input id="billing:is_subscribed_original" type="hidden" name="billing[is_subscribed_original]" value="1" />' +
					'<input id="billing:is_subscribed" type="hidden" name="billing[is_subscribed]" value="1" />');
			
			loadSubscribedField();
		});
	</script>

<?php endif ?>